apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: ClusterIP
  # service is created to allow prometheus to scape endpoints
  clusterIP: None
  selector:
    name: kube-state-metrics
    phase: prod
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8080