kind: Service
apiVersion: v1
metadata:
  namespace: voxxed-days-2018sg-prod
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer     
spec:
  type: LoadBalancer
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31673
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30673
  selector:
    app: rabbitmq