---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: techtalksdb-data
  namespace: voxxed-days-2018sg
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi