apiVersion: v1

kind: Service

metadata:
  name: rabbitmq-consumer
  namespace: voxxed-days-2018sg-prod

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  selector:
    app: rabbitmq-consumer